# Generated by Django 2.2.1 on 2019-05-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Algorithm', '0002_auto_20190518_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
